# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    serializer:
        serialize_null: true
    routing_loader:
        include_format: false
    view:
        view_response_listener: true
        default_engine: twig
        formats:
            json: true
            xml: true
    format_listener:
        rules:
            - { path: '^/api', priorities: ['json'], fallback_format: 'json', prefer_extension: false }
            - { path: '^/', priorities: ['html'], fallback_format: 'html', prefer_extension: false }
    body_listener:
        enabled: true
    param_fetcher_listener:
        enabled: true
    exception:
        enabled: true
        messages:
            'Symfony\Component\HttpKernel\Exception\HttpException' : true
            'Symfony\Component\Security\Core\Exception\BadCredentialsException': true
        codes:
            'Symfony\Component\Security\Core\Exception\BadCredentialsException': 401
        exception_controller: 'fos_rest.exception.controller:showAction'
