version: 2.1
orbs:
  slack: circleci/slack@4.12.5
  ms-teams: cloudradar-monitoring/ms-teams@0.0.1
  kubernetes: circleci/kubernetes@1.3.1
jobs:
  build_frontend:
    working_directory: ~/openex
    docker:
      - image: nikolaik/python-nodejs:python3.10-nodejs18
    resource_class: large
    steps:
      - run:
          command: apt-get update --allow-insecure-repositories --allow-unauthenticated && apt-get install -y build-essential libffi-dev curl
      - checkout
      - run:
          command: |
            git submodule sync
            git submodule update --init --recursive --jobs 8
      - run: 
          working_directory: ~/openex/openex-front
          command: yarn install
      - run:
          working_directory: ~/openex/openex-front
          command: NODE_OPTIONS=--max-old-space-size=8096 yarn build
          no_output_timeout: 30m
      - run: 
          working_directory: ~/
          command: cp -a openex openex_docker && cp -a openex openex_musl
      - slack/notify:
          event: fail
          template: basic_fail_1
      - ms-teams/report:
          only_on_fail: true
          webhook_url: $MS_TEAMS_WEBHOOK_URL
      - persist_to_workspace:
          root: ~/
          paths:
            - openex
            - openex_docker
            - openex_musl
          
  build_platform:
    working_directory: ~/openex
    docker:
      - image: maven:3.8.5-openjdk-18
    steps:
      - attach_workspace:
          at: ~/
      - run: 
          working_directory: ~/openex
          command: mvn install -DskipTests -Pdev
      - slack/notify:
          event: fail
          template: basic_fail_1
      - ms-teams/report:
          only_on_fail: true
          webhook_url: $MS_TEAMS_WEBHOOK_URL
      - persist_to_workspace:
          root: ~/
          paths:
            - openex

  build_platform_musl:
    working_directory: ~/openex_musl
    docker:
      - image: maven:3.8.5-eclipse-temurin-18-alpine
    resource_class: large
    steps:
      - attach_workspace:
          at: ~/
      - run: 
          working_directory: ~/openex_musl
          command: mvn install -DskipTests -Pdev
      - slack/notify:
          event: fail
          template: basic_fail_1
      - ms-teams/report:
          only_on_fail: true
          webhook_url: $MS_TEAMS_WEBHOOK_URL
      - persist_to_workspace:
          root: ~/
          paths:
            - openex_musl

  package_rolling:
    working_directory: ~/openex
    docker:
      - image: maven:3.8.5-openjdk-18
    steps:
      - attach_workspace:
          at: ~/
      - add_ssh_keys
      - run: ssh-keyscan -H openex.io >> ~/.ssh/known_hosts
      - run: git config --global user.email "ci@openex.io" && git config --global user.name "OpenEx CircleCI"
      - run: git remote add openex ssh://git-9qdBths0@openex.io:/~/git-9qdBths0.git && git push --force openex master
      - run: mkdir -p release/openex
      - run: cp -a ./openex-api/target/openex-api.jar release/openex/ && cp -a ./openex-api/src/main/resources/application.properties release/openex/
      - run:
          working_directory: ~/openex/release
          command: tar -zcvf "openex-$(date '+%Y%m%d').tar.gz" openex
      - run:
          working_directory: ~/openex/release
          command: curl -usamuel.hassine@filigran.io:$JFROG_TOKEN -T openex-$(date '+%Y%m%d').tar.gz "https://filigran.jfrog.io/artifactory/openex/openex-$(date '+%Y%m%d').tar.gz"
      - slack/notify:
          event: fail
          template: basic_fail_1
      - ms-teams/report:
          only_on_fail: true
          webhook_url: $MS_TEAMS_WEBHOOK_URL

  package_rolling_musl:
    working_directory: ~/openex_musl
    docker:
      - image: maven:3.8.5-openjdk-18
    steps:
      - attach_workspace:
          at: ~/
      - add_ssh_keys
      - run: ssh-keyscan -H openex.io >> ~/.ssh/known_hosts
      - run: mkdir -p release/openex
      - run: cp -a ./openex-api/target/openex-api.jar release/openex/ && cp -a ./openex-api/src/main/resources/application.properties release/openex/
      - run:
          working_directory: ~/openex_musl/release
          command: tar -zcvf "openex-$(date '+%Y%m%d')_musl.tar.gz" openex
      - run:
          working_directory: ~/openex_musl/release
          command: curl -usamuel.hassine@filigran.io:$JFROG_TOKEN -T openex-$(date '+%Y%m%d')_musl.tar.gz "https://filigran.jfrog.io/artifactory/openex/openex-$(date '+%Y%m%d').tar.gz"
      - slack/notify:
          event: fail
          template: basic_fail_1
      - ms-teams/report:
          only_on_fail: true
          webhook_url: $MS_TEAMS_WEBHOOK_URL

  deploy_testing:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - kubernetes/install-kubectl
      - run: kubectl --server=https://api.staging.eu-west.filigran.io --token=$K8S_TOKEN -n customer-testing rollout restart deployment

  docker_build_platform:
    working_directory: ~/openex_docker
    machine:
      image: ubuntu-2004:202111-02
      resource_class: large
    environment:
      DOCKER_BUILDKIT: 1
      BUILDX_PLATFORMS: linux/amd64,linux/arm64
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Install buildx
          command: |
            BUILDX_BINARY_URL="https://github.com/docker/buildx/releases/download/v0.4.2/buildx-v0.4.2.linux-amd64"
            curl --output docker-buildx \
              --silent --show-error --location --fail --retry 3 \
              "$BUILDX_BINARY_URL"
            mkdir -p ~/.docker/cli-plugins
            mv docker-buildx ~/.docker/cli-plugins/
            chmod a+x ~/.docker/cli-plugins/docker-buildx
            docker buildx install
            # Run binfmt
            docker run --rm --privileged tonistiigi/binfmt:latest --install "$BUILDX_PLATFORMS"
            docker buildx create --name mybuilder --use
      - run:
          name: Login
          command: echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run:
          name: Build Docker image openex/platform
          command: docker buildx build --platform $BUILDX_PLATFORMS -f Dockerfile_circleci -t openexhq/platform:latest -t openexhq/platform:${CIRCLE_TAG} --push .
          no_output_timeout: 30m
      - slack/notify:
          event: fail
          template: basic_fail_1
      - ms-teams/report:
          only_on_fail: true
          webhook_url: $MS_TEAMS_WEBHOOK_URL

  docker_build_platform_rolling:
    working_directory: ~/openex_docker
    machine:
      image: ubuntu-2004:202111-02
      resource_class: large
    environment:
      DOCKER_BUILDKIT: 1
      BUILDX_PLATFORMS: linux/amd64,linux/arm64
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Install buildx
          command: |
            BUILDX_BINARY_URL="https://github.com/docker/buildx/releases/download/v0.4.2/buildx-v0.4.2.linux-amd64"
            curl --output docker-buildx \
              --silent --show-error --location --fail --retry 3 \
              "$BUILDX_BINARY_URL"
            mkdir -p ~/.docker/cli-plugins
            mv docker-buildx ~/.docker/cli-plugins/
            chmod a+x ~/.docker/cli-plugins/docker-buildx
            docker buildx install
            # Run binfmt
            docker run --rm --privileged tonistiigi/binfmt:latest --install "$BUILDX_PLATFORMS"
            docker buildx create --name multiarch --driver docker-container --use
            docker buildx inspect --bootstrap
      - run:
          name: Login
          command: echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run:
          working_directory: ~/openex_docker
          name: Build Docker image openex/platform
          command: docker buildx build --platform $BUILDX_PLATFORMS -f Dockerfile_circleci -t openexhq/platform:rolling --push .
          no_output_timeout: 30
      - slack/notify:
          event: fail
          template: basic_fail_1
      - ms-teams/report:
          only_on_fail: true
          webhook_url: $MS_TEAMS_WEBHOOK_URL
                 
  notify_rolling:
    docker:
      - image: "cimg/base:stable"
    steps:
      - run: sudo apt-get update -qq && sudo apt install curl      
      - slack/notify:
          event: pass
          template: basic_success_1
      - ms-teams/report:
          only_on_fail: false
          webhook_url: $MS_TEAMS_WEBHOOK_URL
  notify:
    docker:
      - image: "cimg/base:stable"
    steps:
      - run: sudo apt-get update -qq && sudo apt install curl   
      - slack/notify:
          event: pass
          template: basic_success_1
      - ms-teams/report:
          only_on_fail: false
          webhook_url: $MS_TEAMS_WEBHOOK_URL       

workflows:
  openex:
    jobs:
      - build_frontend:
          filters:
            tags:
              only: /.*/
      - build_platform:
          filters:
            branches:
              only:
                - master
          requires:
            - build_frontend
      - build_platform_musl:
          filters:
            branches:
              only:
                - master
          requires:
            - build_frontend
      - package_rolling:
          requires:
            - build_platform
          filters:
            branches:
              only:
                - master
      - package_rolling_musl:
          requires:
            - build_platform_musl
          filters:
            branches:
              only:
                - master
      - docker_build_platform_rolling:
          requires:
            - build_frontend
          filters:
            branches:
              only:
                - master
      - docker_build_platform:
          requires:
            - build_frontend
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)+(\.[0-9]+)*/
            branches:
              ignore: /.*/
      - deploy_testing:
          requires:
            - docker_build_platform_rolling
            - docker_build_worker_rolling                
      - notify_rolling:
          requires:
            - deploy_testing
            - package_rolling
            - package_rolling_musl
      - notify:
          requires:
            - docker_build_platform
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)+(\.[0-9]+)*/
            branches:
              ignore: /.*/            